'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace OnePlan3PLServices_Polizas
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="OnePlan3PLServices_Polizas._3PL_PolizasSoap")>  _
    Public Interface _3PL_PolizasSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_Poliza_Header", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_Poliza_Header(ByVal pWhere As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_Poliza_Detail", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_Poliza_Detail(ByVal pWhere As String, ByVal codigoPoliza As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_Sync_Poliza", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_Sync_Poliza(ByVal pPolizaWhere As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/set_Sync_Poliza", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function set_Sync_Poliza(ByVal pPOLIZA As String, ByVal pDOC_ID As Integer, ByVal pCLIENT_CODE As String, ByVal pCLIENT_NAME As String, ByVal pSTATUS As Short, ByVal pSENT As Date, ByVal pRECEIVED As Date, ByVal pSAT_RESULT As String, ByVal pLAST_UPDATED_BY As String, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/set_Shelter", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function set_Shelter(ByVal pDOC_ID As Double, ByVal pISPASS As Integer, ByVal pUPDATED_BY As String, ByVal pEnvironmentName As String, ByRef pResult As String, ByRef pCHECKPOINT_ID As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/set_Poliza_Header", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function set_Poliza_Header( _
                    ByVal pNUMERO_ORDEN As String,  _
                    ByVal pADUANA_ENTRADA_SALIDA As String,  _
                    ByVal pNUMERO_DUA As String,  _
                    ByVal pFECHA_ACEPTACION_DMY As String,  _
                    ByVal pADUANA_DESPACHO_DESTINO As String,  _
                    ByVal pREGIMEN As String,  _
                    ByVal pCLASE As String,  _
                    ByVal pPAIS_PROCEDENCIA As String,  _
                    ByVal pNATURALEZA_TRANS As String,  _
                    ByVal pDEPOSITO_FISCAL_ZF As String,  _
                    ByVal pMODO As Integer,  _
                    ByVal pFECHA_LLEGADA As Date,  _
                    ByVal pTIPO_CAMBIO As Double,  _
                    ByVal pTOTAL_VALOR_ADUANA As Double,  _
                    ByVal pTOTAL_NUMERO_LINEAS As Double,  _
                    ByVal pTOTAL_BULTOS As Integer,  _
                    ByVal pTOTAL_PESO_BRUTO_KG As Double,  _
                    ByVal pTOTAL_FOB_USD As Double,  _
                    ByVal pTOTAL_FLETE_USD As Double,  _
                    ByVal pTOTAL_SEGURO_USD As Double,  _
                    ByVal pTOTAL_OTROS_USD As Double,  _
                    ByVal pNUMERO_SAT As String,  _
                    ByVal pTIPO_IMPORTADOR As String,  _
                    ByVal pID_TRIB_IMPORTADOR As String,  _
                    ByVal pPAIS_IMPORTADOR As String,  _
                    ByVal pRAZON_SOCIAL_IMPORTADOR As String,  _
                    ByVal pDOMICILIO_IMPORTADOR As String,  _
                    ByVal pTIPO_REPRESENTANTE As String,  _
                    ByVal pID_TRIB_REPRESENTANTE As String,  _
                    ByVal pPAIS_REPRESENTANTE As String,  _
                    ByVal pTIPO_DECLARANTE_REPRESENTANTE As String,  _
                    ByVal pRAZON_SOCIAL_REPRESENTANTE As String,  _
                    ByVal pDOMICILIO_REPRESENTANTE As String,  _
                    ByVal pTIPO_CONTENEDOR As Integer,  _
                    ByVal pNUMERO_CONTENEDOR As String,  _
                    ByVal pENTIDAD_CONTENEDOR As String,  _
                    ByVal pNUMERO_MARCHAMO_CONTENEDOR As String,  _
                    ByVal pTOTAL_LIQUIDAR As Double,  _
                    ByVal pTOTAL_OTROS As Double,  _
                    ByVal pTOTAL_GENERAL As Double,  _
                    ByVal pCODIGO_POLIZA As String,  _
                    ByVal pLAST_UPDATED_BY As String,  _
                    ByVal pLAST_UPDATED As Date,  _
                    ByVal pSTATUS As String,  _
                    ByVal pCLIENT_CODE As String,  _
                    ByVal pWAREHOUSE_REGIMEN As String,  _
                    ByVal pFECHA_DOCUMENTO As Date,  _
                    ByVal pACUERDO_COMERCIAL As String,  _
                    ByVal pTIPO As String,  _
                    ByVal pEnvironmentName As String,  _
                    ByRef pResult As String,  _
                    ByRef pDOC_ID As Integer,  _
                    ByVal pPolizaAsegurada As String,  _
                    ByVal pPolizaAssognedto As String,  _
                    ByVal pTranslation As String,  _
                    ByVal pTicketNumber As Long) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/set_Poliza_Detail", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function set_Poliza_Detail( _
                    ByVal pDOC_ID As Integer,  _
                    ByVal pSKU_DESCRIPTION As String,  _
                    ByVal pSAC_CODE As String,  _
                    ByVal pBULTOS As Double,  _
                    ByVal pCLASE As String,  _
                    ByVal pNET_WEIGTH As Double,  _
                    ByVal pWEIGTH_UNIT As String,  _
                    ByVal pQTY As Double,  _
                    ByVal pCUSTOMS_AMOUNT As Double,  _
                    ByVal pQTY_UNIT As String,  _
                    ByVal pVOLUME As Double,  _
                    ByVal pVOLUME_UNIT As String,  _
                    ByVal pDAI As Double,  _
                    ByVal pIVA As Double,  _
                    ByVal pMISC_TAXES As Double,  _
                    ByVal pFOB_USD As Double,  _
                    ByVal pFREIGTH_USD As Double,  _
                    ByVal pINSURANCE_USD As Double,  _
                    ByVal pMISC_EXPENSES As Double,  _
                    ByVal pORIGIN_COUNTRY As String,  _
                    ByVal pREGION_CP As String,  _
                    ByVal pAGREEMENT_1 As String,  _
                    ByVal pAGREEMENT_2 As String,  _
                    ByVal pRELATED_POLIZA As String,  _
                    ByVal pLAST_UPDATED_BY As String,  _
                    ByVal pLAST_UPDATED As Date,  _
                    ByVal pORIGIN_DOC_ID As Integer,  _
                    ByVal pCODIGO_POLIZA_ORIGEN As String,  _
                    ByVal pCLIENT_CODE As String,  _
                    ByVal pPCTDAI As Double,  _
                    ByVal pORIGIN_LINE_NUMBER As Double,  _
                    ByVal pEnvironmentName As String,  _
                    ByRef pResult As String,  _
                    ByRef pLINE_NUMBER As Integer,  _
                    ByVal impuesto As Decimal,  _
                    ByVal materialId As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_Docs_Ref_Poliza", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_Docs_Ref_Poliza(ByVal pWhere As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/set_Docs_Ref_Poliza", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function set_Docs_Ref_Poliza(ByVal pDOC_ID As Integer, ByVal pNUMERO_DUA As String, ByVal pNUMERO_DOCUMENTO As String, ByVal pTIPO_DOCUMENTO As String, ByVal pFECHA_DOCUMENTO As Date, ByVal pOBSERVACIONES As String, ByVal pLAST_UPDATED_BY As String, ByVal pLAST_UPDATED As Date, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/del_Docs_Ref_Poliza", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function del_Docs_Ref_Poliza(ByVal pDOC_ID As Integer, ByVal pNUMERO_DOCUMENTO As String, ByVal pTIPO_DOCUMENTO As String, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_tran_byPoliza", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_tran_byPoliza(ByVal pPOLIZA As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_tran_byID", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_tran_byID(ByVal pTRAN As Double, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_recepcions_pending_auto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_recepcions_pending_auto(ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/set_POLIZA_TRANS_MATCH", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function set_POLIZA_TRANS_MATCH(ByVal pCODIGO_POLIZA As String, ByVal pTRANS_ID As Integer, ByVal pLINENO_POLIZA As Integer, ByVal pDOC_ID As Integer, ByVal pSKU_DESCRIPTION As String, ByVal pMATERIAL_CODE As String, ByVal pMATERIAL_DESCRIPTION As String, ByVal pQTY_TRANS As Double, ByVal pQTY_POLIZA As Double, ByVal pBULTOS_POLIZA As Double, ByVal pLAST_UPDATED_BY As String, ByVal pQty As Double, ByVal pComments As String, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_trans_match", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_trans_match(ByVal pWhere As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/del_POLIZA_TRANS_MATCH", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function del_POLIZA_TRANS_MATCH(ByVal pCODIGO_POLIZA As String, ByVal pMATERIAL_CODE As String, ByVal pLINENO_POLIZA As Integer, ByVal pTRANS_ID As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetInventoryByDosc", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetInventoryByDosc(ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_inventory_bydocs", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_inventory_bydocs(ByVal pWhere As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_cust_term_of_trade", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_cust_term_of_trade(ByVal pCLIENT_CODE As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/del_POLIZA_LINE", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function del_POLIZA_LINE(ByVal pDOC_ID As Integer, ByVal pLINENO_POLIZA As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_cust_skus", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_cust_skus(ByVal pCLIENT_CODE As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_pending_picking", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_pending_picking(ByVal pWHERE As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/set_picking_status", ReplyAction:="*"),
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)>
        Function set_picking_status(ByVal pDOC_ID As Integer, ByVal pLINE_NUMBER As Integer, ByVal pSTATUS As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet

        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/set_pending_quantity", ReplyAction:="*"),
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)>
        Function set_pending_quantity(ByVal pDOC_ID As Integer, ByVal pLINE_NUMBER As Integer, ByVal pPENDING As Decimal, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet

        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_skus_match", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_skus_match(ByVal pWhere As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/set_tasks_list", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function set_tasks_list( _
                    ByVal pTASK_TYPE As String,  _
                    ByVal pTASK_SUBTYPE As String,  _
                    ByVal pTASK_OWNER As String,  _
                    ByVal pTASK_ASSIGNEDTO As String,  _
                    ByVal pQUATITY_ASSIGNED As Double,  _
                    ByVal pQUATITY_PENDING As Double,  _
                    ByVal pCODIGO_POLIZA_SOURCE As String,  _
                    ByVal pCODIGO_POLIZA_TARGET As String,  _
                    ByVal pREGIMEN As String,  _
                    ByVal pMATERIAL_ID As String,  _
                    ByVal pBARCODE_ID As String,  _
                    ByVal pALTERNATE_BARCODE As String,  _
                    ByVal pMATERIAL_NAME As String,  _
                    ByVal pCLIENT_OWNER As String,  _
                    ByVal pCLIENT_NAME As String,  _
                    ByVal numeroDeLineaPolizaOrigen As Integer,  _
                    ByVal numeroDeLineaPolizaDestino As Integer,  _
                    ByVal pEnvironmentName As String,  _
                    ByRef pResult As String,  _
                    ByRef pWAVE_PICKING_ID As Integer,  _
                    ByVal pTranslation As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_all_Poliza_Headers", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_all_Poliza_Headers(ByVal pWhere As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_all_Poliza_Images", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_all_Poliza_Images(ByVal pWhere As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/set_pass", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function set_pass( _
                    ByVal pCLIENT_CODE As String,  _
                    ByVal pCLIENT_NAME As String,  _
                    ByVal pLAST_UPDATED_BY As String,  _
                    ByVal pISEMPTY As String,  _
                    ByVal pVEHICLE_PLATE As String,  _
                    ByVal pVEHICLE_DRIVER As String,  _
                    ByVal pVEHICLE_ID As String,  _
                    ByVal pDRIVER_ID As String,  _
                    ByVal pAUTORIZED_BY As String,  _
                    ByVal pHANDLER As String,  _
                    ByVal pCARRIER As String,  _
                    ByVal pTXT As String,  _
                    ByVal pLOADUNLOAD As String,  _
                    ByVal pLOADWITH As String,  _
                    ByVal pAUDIT_ID As Integer,  _
                    ByVal pEnvironmentName As String,  _
                    ByRef pResult As String,  _
                    ByRef pPASSID As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/set_pass_detail", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function set_pass_detail(ByVal pPASSID As Integer, ByVal pAUDIT_ID As Integer, ByVal pLAST_UPDATED_BY As String, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/set_pass_detail_by_poliza", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function set_pass_detail_by_poliza(ByVal pPASSID As Integer, ByVal pCodePoliza As String, ByVal pLAST_UPDATED_BY As String, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/delete_pass_detail", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function delete_pass_detail(ByVal pPASSID As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/set_poliza_pass", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function set_poliza_pass(ByVal pCLIENT_CODE As String, ByVal pCLIENT_NAME As String, ByVal pLAST_UPDATED_BY As String, ByVal pCODIGO_POLIZA As String, ByVal pNUMERO_ORDEN As String, ByVal pNUMERO_DUA As String, ByVal pDOC_ID As Integer, ByVal pPASSID As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_all_passes", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_all_passes(ByVal pWhere As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_all_poliza_passes", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_all_poliza_passes(ByVal pWhere As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_passes_params", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_passes_params(ByVal pFIELD As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_all_active_logins", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_all_active_logins(ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/set_rectify", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function set_rectify(ByVal pCODIGO_POLIZA As String, ByVal pDOC_ID As Integer, ByVal pCODIGO_POLIZA_RECTIFICADA As String, ByVal pDOC_ID_RECTIFICADA As Integer, ByVal pLAST_UPDATED_BY As String, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetInventoryGeneralByWarehouse", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetInventoryGeneralByWarehouse(ByVal codeClient As String, ByVal codeWarehouse As String, ByVal isDiscretional As Boolean, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetWarehouseByRelatedUsers", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetWarehouseByRelatedUsers(ByVal login As String, ByVal operators As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_general_inventory_by_sku", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_general_inventory_by_sku(ByVal materialId As String, ByVal currentWarehouse As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_general_picking_available", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_general_picking_available(ByVal pWhere As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/set_General_Egreso", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function set_General_Egreso( _
                    ByVal pTASK_OWNER As String,  _
                    ByVal pTASK_ASSIGNEDTO As String,  _
                    ByVal pQUANTITY_ASSIGNED As Double,  _
                    ByVal pCODIGO_POLIZA_TARGET As String,  _
                    ByVal pMATERIAL_ID As String,  _
                    ByVal pBARCODE_ID As String,  _
                    ByVal pALTERNATE_BARCODE As String,  _
                    ByVal pMATERIAL_NAME As String,  _
                    ByVal pCLIENT_OWNER As String,  _
                    ByVal pCLIENT_NAME As String,  _
                    ByVal pEnvironmentName As String,  _
                    ByRef pResult As String,  _
                    ByRef pWPI As Integer,  _
                    ByVal Warehouse As String,  _
                    ByVal EnviarErp As Integer,  _
                    ByVal ProjectId As String,  _
                    ByVal Status As String,  _
                    ByVal pLocationSpotTarget As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/set_General_Egreso_DISCRETIONARY", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function set_General_Egreso_DISCRETIONARY( _
                    ByVal pTASK_OWNER As String,  _
                    ByVal pTASK_ASSIGNEDTO As String,  _
                    ByVal pQUANTITY_ASSIGNED As Double,  _
                    ByVal pCODIGO_POLIZA_TARGET As String,  _
                    ByVal pMATERIAL_ID As String,  _
                    ByVal pBARCODE_ID As String,  _
                    ByVal pALTERNATE_BARCODE As String,  _
                    ByVal pMATERIAL_NAME As String,  _
                    ByVal pCLIENT_OWNER As String,  _
                    ByVal pCLIENT_NAME As String,  _
                    ByVal pEnvironmentName As String,  _
                    ByRef pResult As String,  _
                    ByRef pWPI As Integer,  _
                    ByVal pLicence As Integer,  _
                    ByVal pTypeDiscretionary As String,  _
                    ByVal pSerialNumber As String,  _
                    ByVal tone As String,  _
                    ByVal caliber As String,  _
                    ByVal pProject As String,  _
                    ByVal pLocationSpotTarget As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_all_poliza_kardex", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_all_poliza_kardex(ByVal pTABLA As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_skus_tran_byPoliza", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_skus_tran_byPoliza(ByVal pPOLIZA As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/del_ALL_POLIZA_LINES", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function del_ALL_POLIZA_LINES(ByVal pDOC_ID As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_all_warehouses", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_all_warehouses(ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/print_pass", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function print_pass(ByVal pPASS As Integer, ByVal pAUDIT As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/print_pass_by_poliza", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function print_pass_by_poliza(ByVal pPASS As Integer, ByVal pAUDIT As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/delete_pass_audits_detail", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function delete_pass_audits_detail(ByVal pPASSID As Integer, ByVal pAUDIT_ID As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/delete_pass_detail_by_poliza", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function delete_pass_detail_by_poliza(ByVal pPASSID As Integer, ByVal pCodigoPoliza As String, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetPolizasIngresoFiscal", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetPolizasIngresoFiscal(ByVal pTipo As String, ByVal pRegimen As String, ByVal pValFechas As Boolean, ByVal pFechaInicio As Date, ByVal pFechaFinal As Date, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetRecepcionPendingAuto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetRecepcionPendingAuto(ByVal pCodigoPoliza As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTaskPicking", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetTaskPicking(ByVal pOlaPicking As String, ByVal pMaterialId As String, ByVal pQtyAssigned As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ObtnerConsultaDeEgresos", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ObtnerConsultaDeEgresos(ByVal Login As String, ByVal pFechaInicio As Date, ByVal pFechaFin As Date, ByVal pClientCode As String, ByVal pRegimen As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ObtnerConsultaDeIngreso", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ObtnerConsultaDeIngreso(ByVal Login As String, ByVal pFechaInicio As Date, ByVal pFechaFin As Date, ByVal pClientCode As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ObtnerConsultaDeIngresoGeneral", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ObtnerConsultaDeIngresoGeneral(ByVal Login As String, ByVal pFechaInicio As Date, ByVal pFechaFin As Date, ByVal pClientCode As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Verify_Poliza", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Verify_Poliza(ByVal pPoliza As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Exist_Autorization_Sat", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Exist_Autorization_Sat(ByVal pPoliza As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Create_Autorization_Sat", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Create_Autorization_Sat(ByVal pPoliza As String, ByVal pClientCode As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Update_Autorization_Sat", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Update_Autorization_Sat(ByVal pDocId As Integer, ByVal pSatResult As String, ByVal pSent As Date, ByVal pReceived As Date, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Get_Num_Status", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Get_Num_Status(ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetDocIncomeByClient", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetDocIncomeByClient(ByVal nameTable As String, ByVal codeClient As String, ByVal startDate As Date, ByVal endDate As Date, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetDetailsDocIncomeByClient", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetDetailsDocIncomeByClient(ByVal nameTable As String, ByVal codeClient As String, ByVal codePoliza As String, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EstablecerPolizaPendienteRetificacion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function EstablecerPolizaPendienteRetificacion(ByVal docId As Integer, ByVal poliza As String, ByVal comentario As String, ByVal clase As String, ByVal usuario As String, ByVal pEnvironmentName As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ObtenerPolizasPendientesDeRectificacion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ObtenerPolizasPendientesDeRectificacion(ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EstablecerPolizaRetificacion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function EstablecerPolizaRetificacion(ByVal docIdRectificada As Integer, ByVal docIdRectificacion As Integer, ByVal comentario As String, ByVal clase As String, ByVal usuario As String, ByVal pEnvironmentName As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ObtenerRectificaciones", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ObtenerRectificaciones(ByVal startDate As Date, ByVal endDate As Date, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InsertarTareaDeRecepcion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function InsertarTareaDeRecepcion(ByVal taskSubType As String, ByVal taskOwner As String, ByVal taskAssignedTo As String, ByVal taskComments As String, ByVal regimen As String, ByVal clientOwner As String, ByVal clientName As String, ByVal docIdSource As Integer, ByVal pEnvironmentName As String, ByRef pResult As String, ByVal codigoPolizaSource As String, ByVal EnviaErp As Integer, ByVal priority As Integer, ByVal receptionType As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetPolizaByClientAndWarehouseRegimen", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetPolizaByClientAndWarehouseRegimen(ByVal Login As String, ByVal WarehouseRegimen As String, ByVal ClientCode As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetInventoryFiscalByLicence", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetInventoryFiscalByLicence(ByVal docId As Integer, ByVal line As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InsertTaskFical", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function InsertTaskFical( _
                    ByVal pTASK_TYPE As String,  _
                    ByVal pTASK_SUBTYPE As String,  _
                    ByVal pTASK_OWNER As String,  _
                    ByVal pTASK_ASSIGNEDTO As String,  _
                    ByVal pQUATITY_ASSIGNED As Double,  _
                    ByVal pQUATITY_PENDING As Double,  _
                    ByVal pCODIGO_POLIZA_SOURCE As String,  _
                    ByVal pCODIGO_POLIZA_TARGET As String,  _
                    ByVal pREGIMEN As String,  _
                    ByVal pMATERIAL_ID As String,  _
                    ByVal pBARCODE_ID As String,  _
                    ByVal pALTERNATE_BARCODE As String,  _
                    ByVal pMATERIAL_NAME As String,  _
                    ByVal pCLIENT_OWNER As String,  _
                    ByVal pCLIENT_NAME As String,  _
                    ByVal numeroDeLineaPolizaOrigen As Integer,  _
                    ByVal numeroDeLineaPolizaDestino As Integer,  _
                    ByVal licenciaId As Integer,  _
                    ByVal pEnvironmentName As String,  _
                    ByRef pResult As String,  _
                    ByRef pWAVE_PICKING_ID As Integer,  _
                    ByVal pTranslation As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetInventoryNeededForMasterPack", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetInventoryNeededForMasterPack(ByVal masterPackCode As String, ByVal warehouseId As String, ByVal qty As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CheckMasterPackInventory", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CheckMasterPackInventory(ByVal masterPackCode As String, ByVal warehouseId As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CheckGeneralExitInventory", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CheckGeneralExitInventory(ByVal xmlDetalle As String, ByVal warehouseId As String, ByVal olaPicking As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTaskFromReceptionOrDispatch", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetTaskFromReceptionOrDispatch(ByVal serialNumber As Integer, ByVal wavePickingId As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetPolicyWithAvailableInventory", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetPolicyWithAvailableInventory(ByVal warehouse As String, ByVal clientOwer As String, ByVal regimen As String, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetInventoryByPolicy", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetInventoryByPolicy(ByVal codigoPoliza As String, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTicketById", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetTicketById(ByVal idTicket As Long, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataTable
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface _3PL_PolizasSoapChannel
        Inherits OnePlan3PLServices_Polizas._3PL_PolizasSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class _3PL_PolizasSoapClient
        Inherits System.ServiceModel.ClientBase(Of OnePlan3PLServices_Polizas._3PL_PolizasSoap)
        Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function get_Poliza_Header(ByVal pWhere As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_Poliza_Header
            Return MyBase.Channel.get_Poliza_Header(pWhere, pEnvironmentName, pResult)
        End Function
        
        Public Function get_Poliza_Detail(ByVal pWhere As String, ByVal codigoPoliza As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_Poliza_Detail
            Return MyBase.Channel.get_Poliza_Detail(pWhere, codigoPoliza, pEnvironmentName, pResult)
        End Function
        
        Public Function get_Sync_Poliza(ByVal pPolizaWhere As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_Sync_Poliza
            Return MyBase.Channel.get_Sync_Poliza(pPolizaWhere, pEnvironmentName, pResult)
        End Function
        
        Public Function set_Sync_Poliza(ByVal pPOLIZA As String, ByVal pDOC_ID As Integer, ByVal pCLIENT_CODE As String, ByVal pCLIENT_NAME As String, ByVal pSTATUS As Short, ByVal pSENT As Date, ByVal pRECEIVED As Date, ByVal pSAT_RESULT As String, ByVal pLAST_UPDATED_BY As String, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.set_Sync_Poliza
            Return MyBase.Channel.set_Sync_Poliza(pPOLIZA, pDOC_ID, pCLIENT_CODE, pCLIENT_NAME, pSTATUS, pSENT, pRECEIVED, pSAT_RESULT, pLAST_UPDATED_BY, pEnvironmentName, pResult)
        End Function
        
        Public Function set_Shelter(ByVal pDOC_ID As Double, ByVal pISPASS As Integer, ByVal pUPDATED_BY As String, ByVal pEnvironmentName As String, ByRef pResult As String, ByRef pCHECKPOINT_ID As Integer) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.set_Shelter
            Return MyBase.Channel.set_Shelter(pDOC_ID, pISPASS, pUPDATED_BY, pEnvironmentName, pResult, pCHECKPOINT_ID)
        End Function
        
        Public Function set_Poliza_Header( _
                    ByVal pNUMERO_ORDEN As String,  _
                    ByVal pADUANA_ENTRADA_SALIDA As String,  _
                    ByVal pNUMERO_DUA As String,  _
                    ByVal pFECHA_ACEPTACION_DMY As String,  _
                    ByVal pADUANA_DESPACHO_DESTINO As String,  _
                    ByVal pREGIMEN As String,  _
                    ByVal pCLASE As String,  _
                    ByVal pPAIS_PROCEDENCIA As String,  _
                    ByVal pNATURALEZA_TRANS As String,  _
                    ByVal pDEPOSITO_FISCAL_ZF As String,  _
                    ByVal pMODO As Integer,  _
                    ByVal pFECHA_LLEGADA As Date,  _
                    ByVal pTIPO_CAMBIO As Double,  _
                    ByVal pTOTAL_VALOR_ADUANA As Double,  _
                    ByVal pTOTAL_NUMERO_LINEAS As Double,  _
                    ByVal pTOTAL_BULTOS As Integer,  _
                    ByVal pTOTAL_PESO_BRUTO_KG As Double,  _
                    ByVal pTOTAL_FOB_USD As Double,  _
                    ByVal pTOTAL_FLETE_USD As Double,  _
                    ByVal pTOTAL_SEGURO_USD As Double,  _
                    ByVal pTOTAL_OTROS_USD As Double,  _
                    ByVal pNUMERO_SAT As String,  _
                    ByVal pTIPO_IMPORTADOR As String,  _
                    ByVal pID_TRIB_IMPORTADOR As String,  _
                    ByVal pPAIS_IMPORTADOR As String,  _
                    ByVal pRAZON_SOCIAL_IMPORTADOR As String,  _
                    ByVal pDOMICILIO_IMPORTADOR As String,  _
                    ByVal pTIPO_REPRESENTANTE As String,  _
                    ByVal pID_TRIB_REPRESENTANTE As String,  _
                    ByVal pPAIS_REPRESENTANTE As String,  _
                    ByVal pTIPO_DECLARANTE_REPRESENTANTE As String,  _
                    ByVal pRAZON_SOCIAL_REPRESENTANTE As String,  _
                    ByVal pDOMICILIO_REPRESENTANTE As String,  _
                    ByVal pTIPO_CONTENEDOR As Integer,  _
                    ByVal pNUMERO_CONTENEDOR As String,  _
                    ByVal pENTIDAD_CONTENEDOR As String,  _
                    ByVal pNUMERO_MARCHAMO_CONTENEDOR As String,  _
                    ByVal pTOTAL_LIQUIDAR As Double,  _
                    ByVal pTOTAL_OTROS As Double,  _
                    ByVal pTOTAL_GENERAL As Double,  _
                    ByVal pCODIGO_POLIZA As String,  _
                    ByVal pLAST_UPDATED_BY As String,  _
                    ByVal pLAST_UPDATED As Date,  _
                    ByVal pSTATUS As String,  _
                    ByVal pCLIENT_CODE As String,  _
                    ByVal pWAREHOUSE_REGIMEN As String,  _
                    ByVal pFECHA_DOCUMENTO As Date,  _
                    ByVal pACUERDO_COMERCIAL As String,  _
                    ByVal pTIPO As String,  _
                    ByVal pEnvironmentName As String,  _
                    ByRef pResult As String,  _
                    ByRef pDOC_ID As Integer,  _
                    ByVal pPolizaAsegurada As String,  _
                    ByVal pPolizaAssognedto As String,  _
                    ByVal pTranslation As String,  _
                    ByVal pTicketNumber As Long) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.set_Poliza_Header
            Return MyBase.Channel.set_Poliza_Header(pNUMERO_ORDEN, pADUANA_ENTRADA_SALIDA, pNUMERO_DUA, pFECHA_ACEPTACION_DMY, pADUANA_DESPACHO_DESTINO, pREGIMEN, pCLASE, pPAIS_PROCEDENCIA, pNATURALEZA_TRANS, pDEPOSITO_FISCAL_ZF, pMODO, pFECHA_LLEGADA, pTIPO_CAMBIO, pTOTAL_VALOR_ADUANA, pTOTAL_NUMERO_LINEAS, pTOTAL_BULTOS, pTOTAL_PESO_BRUTO_KG, pTOTAL_FOB_USD, pTOTAL_FLETE_USD, pTOTAL_SEGURO_USD, pTOTAL_OTROS_USD, pNUMERO_SAT, pTIPO_IMPORTADOR, pID_TRIB_IMPORTADOR, pPAIS_IMPORTADOR, pRAZON_SOCIAL_IMPORTADOR, pDOMICILIO_IMPORTADOR, pTIPO_REPRESENTANTE, pID_TRIB_REPRESENTANTE, pPAIS_REPRESENTANTE, pTIPO_DECLARANTE_REPRESENTANTE, pRAZON_SOCIAL_REPRESENTANTE, pDOMICILIO_REPRESENTANTE, pTIPO_CONTENEDOR, pNUMERO_CONTENEDOR, pENTIDAD_CONTENEDOR, pNUMERO_MARCHAMO_CONTENEDOR, pTOTAL_LIQUIDAR, pTOTAL_OTROS, pTOTAL_GENERAL, pCODIGO_POLIZA, pLAST_UPDATED_BY, pLAST_UPDATED, pSTATUS, pCLIENT_CODE, pWAREHOUSE_REGIMEN, pFECHA_DOCUMENTO, pACUERDO_COMERCIAL, pTIPO, pEnvironmentName, pResult, pDOC_ID, pPolizaAsegurada, pPolizaAssognedto, pTranslation, pTicketNumber)
        End Function
        
        Public Function set_Poliza_Detail( _
                    ByVal pDOC_ID As Integer,  _
                    ByVal pSKU_DESCRIPTION As String,  _
                    ByVal pSAC_CODE As String,  _
                    ByVal pBULTOS As Double,  _
                    ByVal pCLASE As String,  _
                    ByVal pNET_WEIGTH As Double,  _
                    ByVal pWEIGTH_UNIT As String,  _
                    ByVal pQTY As Double,  _
                    ByVal pCUSTOMS_AMOUNT As Double,  _
                    ByVal pQTY_UNIT As String,  _
                    ByVal pVOLUME As Double,  _
                    ByVal pVOLUME_UNIT As String,  _
                    ByVal pDAI As Double,  _
                    ByVal pIVA As Double,  _
                    ByVal pMISC_TAXES As Double,  _
                    ByVal pFOB_USD As Double,  _
                    ByVal pFREIGTH_USD As Double,  _
                    ByVal pINSURANCE_USD As Double,  _
                    ByVal pMISC_EXPENSES As Double,  _
                    ByVal pORIGIN_COUNTRY As String,  _
                    ByVal pREGION_CP As String,  _
                    ByVal pAGREEMENT_1 As String,  _
                    ByVal pAGREEMENT_2 As String,  _
                    ByVal pRELATED_POLIZA As String,  _
                    ByVal pLAST_UPDATED_BY As String,  _
                    ByVal pLAST_UPDATED As Date,  _
                    ByVal pORIGIN_DOC_ID As Integer,  _
                    ByVal pCODIGO_POLIZA_ORIGEN As String,  _
                    ByVal pCLIENT_CODE As String,  _
                    ByVal pPCTDAI As Double,  _
                    ByVal pORIGIN_LINE_NUMBER As Double,  _
                    ByVal pEnvironmentName As String,  _
                    ByRef pResult As String,  _
                    ByRef pLINE_NUMBER As Integer,  _
                    ByVal impuesto As Decimal,  _
                    ByVal materialId As String) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.set_Poliza_Detail
            Return MyBase.Channel.set_Poliza_Detail(pDOC_ID, pSKU_DESCRIPTION, pSAC_CODE, pBULTOS, pCLASE, pNET_WEIGTH, pWEIGTH_UNIT, pQTY, pCUSTOMS_AMOUNT, pQTY_UNIT, pVOLUME, pVOLUME_UNIT, pDAI, pIVA, pMISC_TAXES, pFOB_USD, pFREIGTH_USD, pINSURANCE_USD, pMISC_EXPENSES, pORIGIN_COUNTRY, pREGION_CP, pAGREEMENT_1, pAGREEMENT_2, pRELATED_POLIZA, pLAST_UPDATED_BY, pLAST_UPDATED, pORIGIN_DOC_ID, pCODIGO_POLIZA_ORIGEN, pCLIENT_CODE, pPCTDAI, pORIGIN_LINE_NUMBER, pEnvironmentName, pResult, pLINE_NUMBER, impuesto, materialId)
        End Function
        
        Public Function get_Docs_Ref_Poliza(ByVal pWhere As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_Docs_Ref_Poliza
            Return MyBase.Channel.get_Docs_Ref_Poliza(pWhere, pEnvironmentName, pResult)
        End Function
        
        Public Function set_Docs_Ref_Poliza(ByVal pDOC_ID As Integer, ByVal pNUMERO_DUA As String, ByVal pNUMERO_DOCUMENTO As String, ByVal pTIPO_DOCUMENTO As String, ByVal pFECHA_DOCUMENTO As Date, ByVal pOBSERVACIONES As String, ByVal pLAST_UPDATED_BY As String, ByVal pLAST_UPDATED As Date, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.set_Docs_Ref_Poliza
            Return MyBase.Channel.set_Docs_Ref_Poliza(pDOC_ID, pNUMERO_DUA, pNUMERO_DOCUMENTO, pTIPO_DOCUMENTO, pFECHA_DOCUMENTO, pOBSERVACIONES, pLAST_UPDATED_BY, pLAST_UPDATED, pEnvironmentName, pResult)
        End Function
        
        Public Function del_Docs_Ref_Poliza(ByVal pDOC_ID As Integer, ByVal pNUMERO_DOCUMENTO As String, ByVal pTIPO_DOCUMENTO As String, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.del_Docs_Ref_Poliza
            Return MyBase.Channel.del_Docs_Ref_Poliza(pDOC_ID, pNUMERO_DOCUMENTO, pTIPO_DOCUMENTO, pEnvironmentName, pResult)
        End Function
        
        Public Function get_tran_byPoliza(ByVal pPOLIZA As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_tran_byPoliza
            Return MyBase.Channel.get_tran_byPoliza(pPOLIZA, pEnvironmentName, pResult)
        End Function
        
        Public Function get_tran_byID(ByVal pTRAN As Double, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_tran_byID
            Return MyBase.Channel.get_tran_byID(pTRAN, pEnvironmentName, pResult)
        End Function
        
        Public Function get_recepcions_pending_auto(ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_recepcions_pending_auto
            Return MyBase.Channel.get_recepcions_pending_auto(pEnvironmentName, pResult)
        End Function
        
        Public Function set_POLIZA_TRANS_MATCH(ByVal pCODIGO_POLIZA As String, ByVal pTRANS_ID As Integer, ByVal pLINENO_POLIZA As Integer, ByVal pDOC_ID As Integer, ByVal pSKU_DESCRIPTION As String, ByVal pMATERIAL_CODE As String, ByVal pMATERIAL_DESCRIPTION As String, ByVal pQTY_TRANS As Double, ByVal pQTY_POLIZA As Double, ByVal pBULTOS_POLIZA As Double, ByVal pLAST_UPDATED_BY As String, ByVal pQty As Double, ByVal pComments As String, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.set_POLIZA_TRANS_MATCH
            Return MyBase.Channel.set_POLIZA_TRANS_MATCH(pCODIGO_POLIZA, pTRANS_ID, pLINENO_POLIZA, pDOC_ID, pSKU_DESCRIPTION, pMATERIAL_CODE, pMATERIAL_DESCRIPTION, pQTY_TRANS, pQTY_POLIZA, pBULTOS_POLIZA, pLAST_UPDATED_BY, pQty, pComments, pEnvironmentName, pResult)
        End Function
        
        Public Function get_trans_match(ByVal pWhere As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_trans_match
            Return MyBase.Channel.get_trans_match(pWhere, pEnvironmentName, pResult)
        End Function
        
        Public Function del_POLIZA_TRANS_MATCH(ByVal pCODIGO_POLIZA As String, ByVal pMATERIAL_CODE As String, ByVal pLINENO_POLIZA As Integer, ByVal pTRANS_ID As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.del_POLIZA_TRANS_MATCH
            Return MyBase.Channel.del_POLIZA_TRANS_MATCH(pCODIGO_POLIZA, pMATERIAL_CODE, pLINENO_POLIZA, pTRANS_ID, pEnvironmentName, pResult)
        End Function
        
        Public Function GetInventoryByDosc(ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataTable Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.GetInventoryByDosc
            Return MyBase.Channel.GetInventoryByDosc(pEnvironmentName, pResult)
        End Function
        
        Public Function get_inventory_bydocs(ByVal pWhere As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_inventory_bydocs
            Return MyBase.Channel.get_inventory_bydocs(pWhere, pEnvironmentName, pResult)
        End Function
        
        Public Function get_cust_term_of_trade(ByVal pCLIENT_CODE As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_cust_term_of_trade
            Return MyBase.Channel.get_cust_term_of_trade(pCLIENT_CODE, pEnvironmentName, pResult)
        End Function
        
        Public Function del_POLIZA_LINE(ByVal pDOC_ID As Integer, ByVal pLINENO_POLIZA As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.del_POLIZA_LINE
            Return MyBase.Channel.del_POLIZA_LINE(pDOC_ID, pLINENO_POLIZA, pEnvironmentName, pResult)
        End Function
        
        Public Function get_cust_skus(ByVal pCLIENT_CODE As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_cust_skus
            Return MyBase.Channel.get_cust_skus(pCLIENT_CODE, pEnvironmentName, pResult)
        End Function
        
        Public Function get_pending_picking(ByVal pWHERE As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_pending_picking
            Return MyBase.Channel.get_pending_picking(pWHERE, pEnvironmentName, pResult)
        End Function

        Public Function set_picking_status(ByVal pDOC_ID As Integer, ByVal pLINE_NUMBER As Integer, ByVal pSTATUS As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.set_picking_status
            Return MyBase.Channel.set_picking_status(pDOC_ID, pLINE_NUMBER, pSTATUS, pEnvironmentName, pResult)
        End Function

        Public Function set_pending_quantity(ByVal pDOC_ID As Integer, ByVal pLINE_NUMBER As Integer, ByVal pPENDING As Decimal, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.set_pending_quantity
            Return MyBase.Channel.set_pending_quantity(pDOC_ID, pLINE_NUMBER, pPENDING, pEnvironmentName, pResult)
        End Function

        Public Function get_skus_match(ByVal pWhere As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_skus_match
            Return MyBase.Channel.get_skus_match(pWhere, pEnvironmentName, pResult)
        End Function
        
        Public Function set_tasks_list( _
                    ByVal pTASK_TYPE As String,  _
                    ByVal pTASK_SUBTYPE As String,  _
                    ByVal pTASK_OWNER As String,  _
                    ByVal pTASK_ASSIGNEDTO As String,  _
                    ByVal pQUATITY_ASSIGNED As Double,  _
                    ByVal pQUATITY_PENDING As Double,  _
                    ByVal pCODIGO_POLIZA_SOURCE As String,  _
                    ByVal pCODIGO_POLIZA_TARGET As String,  _
                    ByVal pREGIMEN As String,  _
                    ByVal pMATERIAL_ID As String,  _
                    ByVal pBARCODE_ID As String,  _
                    ByVal pALTERNATE_BARCODE As String,  _
                    ByVal pMATERIAL_NAME As String,  _
                    ByVal pCLIENT_OWNER As String,  _
                    ByVal pCLIENT_NAME As String,  _
                    ByVal numeroDeLineaPolizaOrigen As Integer,  _
                    ByVal numeroDeLineaPolizaDestino As Integer,  _
                    ByVal pEnvironmentName As String,  _
                    ByRef pResult As String,  _
                    ByRef pWAVE_PICKING_ID As Integer,  _
                    ByVal pTranslation As String) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.set_tasks_list
            Return MyBase.Channel.set_tasks_list(pTASK_TYPE, pTASK_SUBTYPE, pTASK_OWNER, pTASK_ASSIGNEDTO, pQUATITY_ASSIGNED, pQUATITY_PENDING, pCODIGO_POLIZA_SOURCE, pCODIGO_POLIZA_TARGET, pREGIMEN, pMATERIAL_ID, pBARCODE_ID, pALTERNATE_BARCODE, pMATERIAL_NAME, pCLIENT_OWNER, pCLIENT_NAME, numeroDeLineaPolizaOrigen, numeroDeLineaPolizaDestino, pEnvironmentName, pResult, pWAVE_PICKING_ID, pTranslation)
        End Function
        
        Public Function get_all_Poliza_Headers(ByVal pWhere As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_all_Poliza_Headers
            Return MyBase.Channel.get_all_Poliza_Headers(pWhere, pEnvironmentName, pResult)
        End Function
        
        Public Function get_all_Poliza_Images(ByVal pWhere As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_all_Poliza_Images
            Return MyBase.Channel.get_all_Poliza_Images(pWhere, pEnvironmentName, pResult)
        End Function
        
        Public Function set_pass( _
                    ByVal pCLIENT_CODE As String,  _
                    ByVal pCLIENT_NAME As String,  _
                    ByVal pLAST_UPDATED_BY As String,  _
                    ByVal pISEMPTY As String,  _
                    ByVal pVEHICLE_PLATE As String,  _
                    ByVal pVEHICLE_DRIVER As String,  _
                    ByVal pVEHICLE_ID As String,  _
                    ByVal pDRIVER_ID As String,  _
                    ByVal pAUTORIZED_BY As String,  _
                    ByVal pHANDLER As String,  _
                    ByVal pCARRIER As String,  _
                    ByVal pTXT As String,  _
                    ByVal pLOADUNLOAD As String,  _
                    ByVal pLOADWITH As String,  _
                    ByVal pAUDIT_ID As Integer,  _
                    ByVal pEnvironmentName As String,  _
                    ByRef pResult As String,  _
                    ByRef pPASSID As Integer) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.set_pass
            Return MyBase.Channel.set_pass(pCLIENT_CODE, pCLIENT_NAME, pLAST_UPDATED_BY, pISEMPTY, pVEHICLE_PLATE, pVEHICLE_DRIVER, pVEHICLE_ID, pDRIVER_ID, pAUTORIZED_BY, pHANDLER, pCARRIER, pTXT, pLOADUNLOAD, pLOADWITH, pAUDIT_ID, pEnvironmentName, pResult, pPASSID)
        End Function
        
        Public Function set_pass_detail(ByVal pPASSID As Integer, ByVal pAUDIT_ID As Integer, ByVal pLAST_UPDATED_BY As String, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.set_pass_detail
            Return MyBase.Channel.set_pass_detail(pPASSID, pAUDIT_ID, pLAST_UPDATED_BY, pEnvironmentName, pResult)
        End Function
        
        Public Function set_pass_detail_by_poliza(ByVal pPASSID As Integer, ByVal pCodePoliza As String, ByVal pLAST_UPDATED_BY As String, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.set_pass_detail_by_poliza
            Return MyBase.Channel.set_pass_detail_by_poliza(pPASSID, pCodePoliza, pLAST_UPDATED_BY, pEnvironmentName, pResult)
        End Function
        
        Public Function delete_pass_detail(ByVal pPASSID As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.delete_pass_detail
            Return MyBase.Channel.delete_pass_detail(pPASSID, pEnvironmentName, pResult)
        End Function
        
        Public Function set_poliza_pass(ByVal pCLIENT_CODE As String, ByVal pCLIENT_NAME As String, ByVal pLAST_UPDATED_BY As String, ByVal pCODIGO_POLIZA As String, ByVal pNUMERO_ORDEN As String, ByVal pNUMERO_DUA As String, ByVal pDOC_ID As Integer, ByVal pPASSID As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.set_poliza_pass
            Return MyBase.Channel.set_poliza_pass(pCLIENT_CODE, pCLIENT_NAME, pLAST_UPDATED_BY, pCODIGO_POLIZA, pNUMERO_ORDEN, pNUMERO_DUA, pDOC_ID, pPASSID, pEnvironmentName, pResult)
        End Function
        
        Public Function get_all_passes(ByVal pWhere As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_all_passes
            Return MyBase.Channel.get_all_passes(pWhere, pEnvironmentName, pResult)
        End Function
        
        Public Function get_all_poliza_passes(ByVal pWhere As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_all_poliza_passes
            Return MyBase.Channel.get_all_poliza_passes(pWhere, pEnvironmentName, pResult)
        End Function
        
        Public Function get_passes_params(ByVal pFIELD As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_passes_params
            Return MyBase.Channel.get_passes_params(pFIELD, pEnvironmentName, pResult)
        End Function
        
        Public Function get_all_active_logins(ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_all_active_logins
            Return MyBase.Channel.get_all_active_logins(pEnvironmentName, pResult)
        End Function
        
        Public Function set_rectify(ByVal pCODIGO_POLIZA As String, ByVal pDOC_ID As Integer, ByVal pCODIGO_POLIZA_RECTIFICADA As String, ByVal pDOC_ID_RECTIFICADA As Integer, ByVal pLAST_UPDATED_BY As String, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.set_rectify
            Return MyBase.Channel.set_rectify(pCODIGO_POLIZA, pDOC_ID, pCODIGO_POLIZA_RECTIFICADA, pDOC_ID_RECTIFICADA, pLAST_UPDATED_BY, pEnvironmentName, pResult)
        End Function
        
        Public Function GetInventoryGeneralByWarehouse(ByVal codeClient As String, ByVal codeWarehouse As String, ByVal isDiscretional As Boolean, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataTable Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.GetInventoryGeneralByWarehouse
            Return MyBase.Channel.GetInventoryGeneralByWarehouse(codeClient, codeWarehouse, isDiscretional, pEnvironmentName, pResult)
        End Function
        
        Public Function GetWarehouseByRelatedUsers(ByVal login As String, ByVal operators As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataTable Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.GetWarehouseByRelatedUsers
            Return MyBase.Channel.GetWarehouseByRelatedUsers(login, operators, pEnvironmentName, pResult)
        End Function
        
        Public Function get_general_inventory_by_sku(ByVal materialId As String, ByVal currentWarehouse As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataTable Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_general_inventory_by_sku
            Return MyBase.Channel.get_general_inventory_by_sku(materialId, currentWarehouse, pEnvironmentName, pResult)
        End Function
        
        Public Function get_general_picking_available(ByVal pWhere As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_general_picking_available
            Return MyBase.Channel.get_general_picking_available(pWhere, pEnvironmentName, pResult)
        End Function
        
        Public Function set_General_Egreso( _
                    ByVal pTASK_OWNER As String,  _
                    ByVal pTASK_ASSIGNEDTO As String,  _
                    ByVal pQUANTITY_ASSIGNED As Double,  _
                    ByVal pCODIGO_POLIZA_TARGET As String,  _
                    ByVal pMATERIAL_ID As String,  _
                    ByVal pBARCODE_ID As String,  _
                    ByVal pALTERNATE_BARCODE As String,  _
                    ByVal pMATERIAL_NAME As String,  _
                    ByVal pCLIENT_OWNER As String,  _
                    ByVal pCLIENT_NAME As String,  _
                    ByVal pEnvironmentName As String,  _
                    ByRef pResult As String,  _
                    ByRef pWPI As Integer,  _
                    ByVal Warehouse As String,  _
                    ByVal EnviarErp As Integer,  _
                    ByVal ProjectId As String,  _
                    ByVal Status As String,  _
                    ByVal pLocationSpotTarget As String) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.set_General_Egreso
            Return MyBase.Channel.set_General_Egreso(pTASK_OWNER, pTASK_ASSIGNEDTO, pQUANTITY_ASSIGNED, pCODIGO_POLIZA_TARGET, pMATERIAL_ID, pBARCODE_ID, pALTERNATE_BARCODE, pMATERIAL_NAME, pCLIENT_OWNER, pCLIENT_NAME, pEnvironmentName, pResult, pWPI, Warehouse, EnviarErp, ProjectId, Status, pLocationSpotTarget)
        End Function
        
        Public Function set_General_Egreso_DISCRETIONARY( _
                    ByVal pTASK_OWNER As String,  _
                    ByVal pTASK_ASSIGNEDTO As String,  _
                    ByVal pQUANTITY_ASSIGNED As Double,  _
                    ByVal pCODIGO_POLIZA_TARGET As String,  _
                    ByVal pMATERIAL_ID As String,  _
                    ByVal pBARCODE_ID As String,  _
                    ByVal pALTERNATE_BARCODE As String,  _
                    ByVal pMATERIAL_NAME As String,  _
                    ByVal pCLIENT_OWNER As String,  _
                    ByVal pCLIENT_NAME As String,  _
                    ByVal pEnvironmentName As String,  _
                    ByRef pResult As String,  _
                    ByRef pWPI As Integer,  _
                    ByVal pLicence As Integer,  _
                    ByVal pTypeDiscretionary As String,  _
                    ByVal pSerialNumber As String,  _
                    ByVal tone As String,  _
                    ByVal caliber As String,  _
                    ByVal pProject As String,  _
                    ByVal pLocationSpotTarget As String) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.set_General_Egreso_DISCRETIONARY
            Return MyBase.Channel.set_General_Egreso_DISCRETIONARY(pTASK_OWNER, pTASK_ASSIGNEDTO, pQUANTITY_ASSIGNED, pCODIGO_POLIZA_TARGET, pMATERIAL_ID, pBARCODE_ID, pALTERNATE_BARCODE, pMATERIAL_NAME, pCLIENT_OWNER, pCLIENT_NAME, pEnvironmentName, pResult, pWPI, pLicence, pTypeDiscretionary, pSerialNumber, tone, caliber, pProject, pLocationSpotTarget)
        End Function
        
        Public Function get_all_poliza_kardex(ByVal pTABLA As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataTable Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_all_poliza_kardex
            Return MyBase.Channel.get_all_poliza_kardex(pTABLA, pEnvironmentName, pResult)
        End Function
        
        Public Function get_skus_tran_byPoliza(ByVal pPOLIZA As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_skus_tran_byPoliza
            Return MyBase.Channel.get_skus_tran_byPoliza(pPOLIZA, pEnvironmentName, pResult)
        End Function
        
        Public Function del_ALL_POLIZA_LINES(ByVal pDOC_ID As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.del_ALL_POLIZA_LINES
            Return MyBase.Channel.del_ALL_POLIZA_LINES(pDOC_ID, pEnvironmentName, pResult)
        End Function
        
        Public Function get_all_warehouses(ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.get_all_warehouses
            Return MyBase.Channel.get_all_warehouses(pEnvironmentName, pResult)
        End Function
        
        Public Function print_pass(ByVal pPASS As Integer, ByVal pAUDIT As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.print_pass
            Return MyBase.Channel.print_pass(pPASS, pAUDIT, pEnvironmentName, pResult)
        End Function
        
        Public Function print_pass_by_poliza(ByVal pPASS As Integer, ByVal pAUDIT As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.print_pass_by_poliza
            Return MyBase.Channel.print_pass_by_poliza(pPASS, pAUDIT, pEnvironmentName, pResult)
        End Function
        
        Public Function delete_pass_audits_detail(ByVal pPASSID As Integer, ByVal pAUDIT_ID As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.delete_pass_audits_detail
            Return MyBase.Channel.delete_pass_audits_detail(pPASSID, pAUDIT_ID, pEnvironmentName, pResult)
        End Function
        
        Public Function delete_pass_detail_by_poliza(ByVal pPASSID As Integer, ByVal pCodigoPoliza As String, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.delete_pass_detail_by_poliza
            Return MyBase.Channel.delete_pass_detail_by_poliza(pPASSID, pCodigoPoliza, pEnvironmentName, pResult)
        End Function
        
        Public Function GetPolizasIngresoFiscal(ByVal pTipo As String, ByVal pRegimen As String, ByVal pValFechas As Boolean, ByVal pFechaInicio As Date, ByVal pFechaFinal As Date, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataTable Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.GetPolizasIngresoFiscal
            Return MyBase.Channel.GetPolizasIngresoFiscal(pTipo, pRegimen, pValFechas, pFechaInicio, pFechaFinal, pEnvironmentName, pResult)
        End Function
        
        Public Function GetRecepcionPendingAuto(ByVal pCodigoPoliza As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataTable Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.GetRecepcionPendingAuto
            Return MyBase.Channel.GetRecepcionPendingAuto(pCodigoPoliza, pEnvironmentName, pResult)
        End Function
        
        Public Function GetTaskPicking(ByVal pOlaPicking As String, ByVal pMaterialId As String, ByVal pQtyAssigned As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataTable Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.GetTaskPicking
            Return MyBase.Channel.GetTaskPicking(pOlaPicking, pMaterialId, pQtyAssigned, pEnvironmentName, pResult)
        End Function
        
        Public Function ObtnerConsultaDeEgresos(ByVal Login As String, ByVal pFechaInicio As Date, ByVal pFechaFin As Date, ByVal pClientCode As String, ByVal pRegimen As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataTable Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.ObtnerConsultaDeEgresos
            Return MyBase.Channel.ObtnerConsultaDeEgresos(Login, pFechaInicio, pFechaFin, pClientCode, pRegimen, pEnvironmentName, pResult)
        End Function
        
        Public Function ObtnerConsultaDeIngreso(ByVal Login As String, ByVal pFechaInicio As Date, ByVal pFechaFin As Date, ByVal pClientCode As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataTable Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.ObtnerConsultaDeIngreso
            Return MyBase.Channel.ObtnerConsultaDeIngreso(Login, pFechaInicio, pFechaFin, pClientCode, pEnvironmentName, pResult)
        End Function
        
        Public Function ObtnerConsultaDeIngresoGeneral(ByVal Login As String, ByVal pFechaInicio As Date, ByVal pFechaFin As Date, ByVal pClientCode As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataTable Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.ObtnerConsultaDeIngresoGeneral
            Return MyBase.Channel.ObtnerConsultaDeIngresoGeneral(Login, pFechaInicio, pFechaFin, pClientCode, pEnvironmentName, pResult)
        End Function
        
        Public Function Verify_Poliza(ByVal pPoliza As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.Verify_Poliza
            Return MyBase.Channel.Verify_Poliza(pPoliza, pEnvironmentName, pResult)
        End Function
        
        Public Function Exist_Autorization_Sat(ByVal pPoliza As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.Exist_Autorization_Sat
            Return MyBase.Channel.Exist_Autorization_Sat(pPoliza, pEnvironmentName, pResult)
        End Function
        
        Public Function Create_Autorization_Sat(ByVal pPoliza As String, ByVal pClientCode As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.Create_Autorization_Sat
            Return MyBase.Channel.Create_Autorization_Sat(pPoliza, pClientCode, pEnvironmentName, pResult)
        End Function
        
        Public Function Update_Autorization_Sat(ByVal pDocId As Integer, ByVal pSatResult As String, ByVal pSent As Date, ByVal pReceived As Date, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.Update_Autorization_Sat
            Return MyBase.Channel.Update_Autorization_Sat(pDocId, pSatResult, pSent, pReceived, pEnvironmentName, pResult)
        End Function
        
        Public Function Get_Num_Status(ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.Get_Num_Status
            Return MyBase.Channel.Get_Num_Status(pEnvironmentName, pResult)
        End Function
        
        Public Function GetDocIncomeByClient(ByVal nameTable As String, ByVal codeClient As String, ByVal startDate As Date, ByVal endDate As Date, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataTable Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.GetDocIncomeByClient
            Return MyBase.Channel.GetDocIncomeByClient(nameTable, codeClient, startDate, endDate, pResult, pEnvironmentName)
        End Function
        
        Public Function GetDetailsDocIncomeByClient(ByVal nameTable As String, ByVal codeClient As String, ByVal codePoliza As String, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataTable Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.GetDetailsDocIncomeByClient
            Return MyBase.Channel.GetDetailsDocIncomeByClient(nameTable, codeClient, codePoliza, pResult, pEnvironmentName)
        End Function
        
        Public Function EstablecerPolizaPendienteRetificacion(ByVal docId As Integer, ByVal poliza As String, ByVal comentario As String, ByVal clase As String, ByVal usuario As String, ByVal pEnvironmentName As String) As String Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.EstablecerPolizaPendienteRetificacion
            Return MyBase.Channel.EstablecerPolizaPendienteRetificacion(docId, poliza, comentario, clase, usuario, pEnvironmentName)
        End Function
        
        Public Function ObtenerPolizasPendientesDeRectificacion(ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataTable Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.ObtenerPolizasPendientesDeRectificacion
            Return MyBase.Channel.ObtenerPolizasPendientesDeRectificacion(pResult, pEnvironmentName)
        End Function
        
        Public Function EstablecerPolizaRetificacion(ByVal docIdRectificada As Integer, ByVal docIdRectificacion As Integer, ByVal comentario As String, ByVal clase As String, ByVal usuario As String, ByVal pEnvironmentName As String) As String Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.EstablecerPolizaRetificacion
            Return MyBase.Channel.EstablecerPolizaRetificacion(docIdRectificada, docIdRectificacion, comentario, clase, usuario, pEnvironmentName)
        End Function
        
        Public Function ObtenerRectificaciones(ByVal startDate As Date, ByVal endDate As Date, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataTable Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.ObtenerRectificaciones
            Return MyBase.Channel.ObtenerRectificaciones(startDate, endDate, pResult, pEnvironmentName)
        End Function
        
        Public Function InsertarTareaDeRecepcion(ByVal taskSubType As String, ByVal taskOwner As String, ByVal taskAssignedTo As String, ByVal taskComments As String, ByVal regimen As String, ByVal clientOwner As String, ByVal clientName As String, ByVal docIdSource As Integer, ByVal pEnvironmentName As String, ByRef pResult As String, ByVal codigoPolizaSource As String, ByVal EnviaErp As Integer, ByVal priority As Integer, ByVal receptionType As String) As System.Data.DataTable Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.InsertarTareaDeRecepcion
            Return MyBase.Channel.InsertarTareaDeRecepcion(taskSubType, taskOwner, taskAssignedTo, taskComments, regimen, clientOwner, clientName, docIdSource, pEnvironmentName, pResult, codigoPolizaSource, EnviaErp, priority, receptionType)
        End Function
        
        Public Function GetPolizaByClientAndWarehouseRegimen(ByVal Login As String, ByVal WarehouseRegimen As String, ByVal ClientCode As String, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.GetPolizaByClientAndWarehouseRegimen
            Return MyBase.Channel.GetPolizaByClientAndWarehouseRegimen(Login, WarehouseRegimen, ClientCode, pEnvironmentName, pResult)
        End Function
        
        Public Function GetInventoryFiscalByLicence(ByVal docId As Integer, ByVal line As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataTable Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.GetInventoryFiscalByLicence
            Return MyBase.Channel.GetInventoryFiscalByLicence(docId, line, pResult, pEnvironmentName)
        End Function
        
        Public Function InsertTaskFical( _
                    ByVal pTASK_TYPE As String,  _
                    ByVal pTASK_SUBTYPE As String,  _
                    ByVal pTASK_OWNER As String,  _
                    ByVal pTASK_ASSIGNEDTO As String,  _
                    ByVal pQUATITY_ASSIGNED As Double,  _
                    ByVal pQUATITY_PENDING As Double,  _
                    ByVal pCODIGO_POLIZA_SOURCE As String,  _
                    ByVal pCODIGO_POLIZA_TARGET As String,  _
                    ByVal pREGIMEN As String,  _
                    ByVal pMATERIAL_ID As String,  _
                    ByVal pBARCODE_ID As String,  _
                    ByVal pALTERNATE_BARCODE As String,  _
                    ByVal pMATERIAL_NAME As String,  _
                    ByVal pCLIENT_OWNER As String,  _
                    ByVal pCLIENT_NAME As String,  _
                    ByVal numeroDeLineaPolizaOrigen As Integer,  _
                    ByVal numeroDeLineaPolizaDestino As Integer,  _
                    ByVal licenciaId As Integer,  _
                    ByVal pEnvironmentName As String,  _
                    ByRef pResult As String,  _
                    ByRef pWAVE_PICKING_ID As Integer,  _
                    ByVal pTranslation As String) As Boolean Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.InsertTaskFical
            Return MyBase.Channel.InsertTaskFical(pTASK_TYPE, pTASK_SUBTYPE, pTASK_OWNER, pTASK_ASSIGNEDTO, pQUATITY_ASSIGNED, pQUATITY_PENDING, pCODIGO_POLIZA_SOURCE, pCODIGO_POLIZA_TARGET, pREGIMEN, pMATERIAL_ID, pBARCODE_ID, pALTERNATE_BARCODE, pMATERIAL_NAME, pCLIENT_OWNER, pCLIENT_NAME, numeroDeLineaPolizaOrigen, numeroDeLineaPolizaDestino, licenciaId, pEnvironmentName, pResult, pWAVE_PICKING_ID, pTranslation)
        End Function
        
        Public Function GetInventoryNeededForMasterPack(ByVal masterPackCode As String, ByVal warehouseId As String, ByVal qty As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataTable Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.GetInventoryNeededForMasterPack
            Return MyBase.Channel.GetInventoryNeededForMasterPack(masterPackCode, warehouseId, qty, pResult, pEnvironmentName)
        End Function
        
        Public Function CheckMasterPackInventory(ByVal masterPackCode As String, ByVal warehouseId As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Integer Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.CheckMasterPackInventory
            Return MyBase.Channel.CheckMasterPackInventory(masterPackCode, warehouseId, pResult, pEnvironmentName)
        End Function
        
        Public Function CheckGeneralExitInventory(ByVal xmlDetalle As String, ByVal warehouseId As String, ByVal olaPicking As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataSet Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.CheckGeneralExitInventory
            Return MyBase.Channel.CheckGeneralExitInventory(xmlDetalle, warehouseId, olaPicking, pResult, pEnvironmentName)
        End Function
        
        Public Function GetTaskFromReceptionOrDispatch(ByVal serialNumber As Integer, ByVal wavePickingId As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataTable Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.GetTaskFromReceptionOrDispatch
            Return MyBase.Channel.GetTaskFromReceptionOrDispatch(serialNumber, wavePickingId, pResult, pEnvironmentName)
        End Function
        
        Public Function GetPolicyWithAvailableInventory(ByVal warehouse As String, ByVal clientOwer As String, ByVal regimen As String, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataTable Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.GetPolicyWithAvailableInventory
            Return MyBase.Channel.GetPolicyWithAvailableInventory(warehouse, clientOwer, regimen, pResult, pEnvironmentName)
        End Function
        
        Public Function GetInventoryByPolicy(ByVal codigoPoliza As String, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataTable Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.GetInventoryByPolicy
            Return MyBase.Channel.GetInventoryByPolicy(codigoPoliza, pResult, pEnvironmentName)
        End Function
        
        Public Function GetTicketById(ByVal idTicket As Long, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataTable Implements OnePlan3PLServices_Polizas._3PL_PolizasSoap.GetTicketById
            Return MyBase.Channel.GetTicketById(idTicket, pResult, pEnvironmentName)
        End Function
    End Class
End Namespace
