'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace WMS_Polizas
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WMS_Polizas.WMS_PolizasSoap")>  _
    Public Interface WMS_PolizasSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ParsePoliza", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ParsePoliza(ByVal pPOLIZA_BARCODE As String, ByRef pResult As String) As System.Data.DataSet
        
        'CODEGEN: Parameter 'pIMAGE' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AgregarImagenAPoliza", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function AgregarImagenAPoliza(ByVal request As WMS_Polizas.AgregarImagenAPolizaRequest) As WMS_Polizas.AgregarImagenAPolizaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CrearLicencia", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CrearLicencia(ByVal pCODIGO_POLIZA As String, ByVal pLoginID As String, ByRef pLICENCIA_ID As Integer, ByVal pCLIENT_OWNER As String, ByVal pREGIMEN As String, ByVal TaskId As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AgregaSKU_Licencia", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function AgregaSKU_Licencia( _
                    ByVal pLICENSE_ID As Integer,  _
                    ByVal pBARCODE As String,  _
                    ByVal pQTY As Decimal,  _
                    ByVal pLAST_LOGIN As String,  _
                    ByVal pVOLUME_FACTOR As Double,  _
                    ByVal pWEIGTH As Double,  _
                    ByVal pSERIAL As String,  _
                    ByVal pCOMMENTS As String,  _
                    ByVal pACUERDO_COMERCIAL As String,  _
                    ByRef pSKUS_COUNTED As Integer,  _
                    ByVal pSTATUS As String,  _
                    ByRef pResult As String,  _
                    ByVal pEnvironmentName As String,  _
                    ByVal pDateExpiration As Date,  _
                    ByVal pBatch As String,  _
                    ByVal pVin As String,  _
                    ByVal statusName As String,  _
                    ByVal action As String,  _
                    ByVal tone As String,  _
                    ByVal caliber As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdatePolizaImg", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UpdatePolizaImg(ByVal pPhotoId As Integer, ByVal pComment As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AgregarSeriePorMaterial", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function AgregarSeriePorMaterial(ByVal licenciaId As Integer, ByVal materialId As String, ByVal serie As String, ByVal batch As String, ByVal fechaDeExpiracion As Date, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ActulizarLoteYFechaDeVencimientoPorSerie", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ActulizarLoteYFechaDeVencimientoPorSerie(ByVal correlativo As Integer, ByVal batch As Integer, ByVal fechaDeExpiracion As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EliminarSerie", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function EliminarSerie(ByVal correlativo As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ObtienerInformacionPorMaterialSerie", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ObtienerInformacionPorMaterialSerie(ByVal materialId As String, ByVal serie As String, ByVal licenseId As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataTable
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="AgregarImagenAPoliza", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class AgregarImagenAPolizaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public pCODIGO_BARRAS_ID As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public pIMAGE() As Byte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public pLoginID As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)>  _
        Public pAuditId As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=4)>  _
        Public pAuditType As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=5)>  _
        Public pResult As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=6)>  _
        Public pEnvironmentName As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pCODIGO_BARRAS_ID As String, ByVal pIMAGE() As Byte, ByVal pLoginID As String, ByVal pAuditId As Integer, ByVal pAuditType As String, ByVal pResult As String, ByVal pEnvironmentName As String)
            MyBase.New
            Me.pCODIGO_BARRAS_ID = pCODIGO_BARRAS_ID
            Me.pIMAGE = pIMAGE
            Me.pLoginID = pLoginID
            Me.pAuditId = pAuditId
            Me.pAuditType = pAuditType
            Me.pResult = pResult
            Me.pEnvironmentName = pEnvironmentName
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="AgregarImagenAPolizaResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class AgregarImagenAPolizaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public AgregarImagenAPolizaResult As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public pResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AgregarImagenAPolizaResult As Boolean, ByVal pResult As String)
            MyBase.New
            Me.AgregarImagenAPolizaResult = AgregarImagenAPolizaResult
            Me.pResult = pResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WMS_PolizasSoapChannel
        Inherits WMS_Polizas.WMS_PolizasSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WMS_PolizasSoapClient
        Inherits System.ServiceModel.ClientBase(Of WMS_Polizas.WMS_PolizasSoap)
        Implements WMS_Polizas.WMS_PolizasSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ParsePoliza(ByVal pPOLIZA_BARCODE As String, ByRef pResult As String) As System.Data.DataSet Implements WMS_Polizas.WMS_PolizasSoap.ParsePoliza
            Return MyBase.Channel.ParsePoliza(pPOLIZA_BARCODE, pResult)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WMS_Polizas_WMS_PolizasSoap_AgregarImagenAPoliza(ByVal request As WMS_Polizas.AgregarImagenAPolizaRequest) As WMS_Polizas.AgregarImagenAPolizaResponse Implements WMS_Polizas.WMS_PolizasSoap.AgregarImagenAPoliza
            Return MyBase.Channel.AgregarImagenAPoliza(request)
        End Function
        
        Public Function AgregarImagenAPoliza(ByVal pCODIGO_BARRAS_ID As String, ByVal pIMAGE() As Byte, ByVal pLoginID As String, ByVal pAuditId As Integer, ByVal pAuditType As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
            Dim inValue As WMS_Polizas.AgregarImagenAPolizaRequest = New WMS_Polizas.AgregarImagenAPolizaRequest()
            inValue.pCODIGO_BARRAS_ID = pCODIGO_BARRAS_ID
            inValue.pIMAGE = pIMAGE
            inValue.pLoginID = pLoginID
            inValue.pAuditId = pAuditId
            inValue.pAuditType = pAuditType
            inValue.pResult = pResult
            inValue.pEnvironmentName = pEnvironmentName
            Dim retVal As WMS_Polizas.AgregarImagenAPolizaResponse = CType(Me,WMS_Polizas.WMS_PolizasSoap).AgregarImagenAPoliza(inValue)
            pResult = retVal.pResult
            Return retVal.AgregarImagenAPolizaResult
        End Function
        
        Public Function CrearLicencia(ByVal pCODIGO_POLIZA As String, ByVal pLoginID As String, ByRef pLICENCIA_ID As Integer, ByVal pCLIENT_OWNER As String, ByVal pREGIMEN As String, ByVal TaskId As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements WMS_Polizas.WMS_PolizasSoap.CrearLicencia
            Return MyBase.Channel.CrearLicencia(pCODIGO_POLIZA, pLoginID, pLICENCIA_ID, pCLIENT_OWNER, pREGIMEN, TaskId, pResult, pEnvironmentName)
        End Function
        
        Public Function AgregaSKU_Licencia( _
                    ByVal pLICENSE_ID As Integer,  _
                    ByVal pBARCODE As String,  _
                    ByVal pQTY As Decimal,  _
                    ByVal pLAST_LOGIN As String,  _
                    ByVal pVOLUME_FACTOR As Double,  _
                    ByVal pWEIGTH As Double,  _
                    ByVal pSERIAL As String,  _
                    ByVal pCOMMENTS As String,  _
                    ByVal pACUERDO_COMERCIAL As String,  _
                    ByRef pSKUS_COUNTED As Integer,  _
                    ByVal pSTATUS As String,  _
                    ByRef pResult As String,  _
                    ByVal pEnvironmentName As String,  _
                    ByVal pDateExpiration As Date,  _
                    ByVal pBatch As String,  _
                    ByVal pVin As String,  _
                    ByVal statusName As String,  _
                    ByVal action As String,  _
                    ByVal tone As String,  _
                    ByVal caliber As String) As Boolean Implements WMS_Polizas.WMS_PolizasSoap.AgregaSKU_Licencia
            Return MyBase.Channel.AgregaSKU_Licencia(pLICENSE_ID, pBARCODE, pQTY, pLAST_LOGIN, pVOLUME_FACTOR, pWEIGTH, pSERIAL, pCOMMENTS, pACUERDO_COMERCIAL, pSKUS_COUNTED, pSTATUS, pResult, pEnvironmentName, pDateExpiration, pBatch, pVin, statusName, action, tone, caliber)
        End Function
        
        Public Function UpdatePolizaImg(ByVal pPhotoId As Integer, ByVal pComment As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements WMS_Polizas.WMS_PolizasSoap.UpdatePolizaImg
            Return MyBase.Channel.UpdatePolizaImg(pPhotoId, pComment, pResult, pEnvironmentName)
        End Function
        
        Public Function AgregarSeriePorMaterial(ByVal licenciaId As Integer, ByVal materialId As String, ByVal serie As String, ByVal batch As String, ByVal fechaDeExpiracion As Date, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements WMS_Polizas.WMS_PolizasSoap.AgregarSeriePorMaterial
            Return MyBase.Channel.AgregarSeriePorMaterial(licenciaId, materialId, serie, batch, fechaDeExpiracion, pResult, pEnvironmentName)
        End Function
        
        Public Function ActulizarLoteYFechaDeVencimientoPorSerie(ByVal correlativo As Integer, ByVal batch As Integer, ByVal fechaDeExpiracion As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements WMS_Polizas.WMS_PolizasSoap.ActulizarLoteYFechaDeVencimientoPorSerie
            Return MyBase.Channel.ActulizarLoteYFechaDeVencimientoPorSerie(correlativo, batch, fechaDeExpiracion, pResult, pEnvironmentName)
        End Function
        
        Public Function EliminarSerie(ByVal correlativo As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements WMS_Polizas.WMS_PolizasSoap.EliminarSerie
            Return MyBase.Channel.EliminarSerie(correlativo, pResult, pEnvironmentName)
        End Function
        
        Public Function ObtienerInformacionPorMaterialSerie(ByVal materialId As String, ByVal serie As String, ByVal licenseId As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataTable Implements WMS_Polizas.WMS_PolizasSoap.ObtienerInformacionPorMaterialSerie
            Return MyBase.Channel.ObtienerInformacionPorMaterialSerie(materialId, serie, licenseId, pResult, pEnvironmentName)
        End Function
    End Class
End Namespace
