'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace OnePlanServices_ServicesToBill
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="OnePlanServices_ServicesToBill.WMS_ServicesToBillSoap")>  _
    Public Interface WMS_ServicesToBillSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetAllServicesNotRelated", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetAllServicesNotRelated(ByVal pCLIENT_ERP_CODE As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetAllServicesRelatedTo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetAllServicesRelatedTo(ByVal pCLIENT_ERP_CODE As String, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RelateServiceTo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RelateServiceTo(ByVal pCLIENT_ERP_CODE As String, ByVal pSERVICE_ID As String, ByVal pLOGIN_ID As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UnRelateServiceTo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UnRelateServiceTo(ByVal pCLIENT_ERP_CODE As String, ByVal pSERVICE_SEQUENCE As Integer, ByVal pLOGIN_ID As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateServiceComments", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UpdateServiceComments(ByVal pCLIENT_ERP_CODE As String, ByVal pSERVICE_ID As String, ByVal pCOMMENTS As String, ByVal pREFERENCES As String, ByVal pLOGIN_ID As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateService", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UpdateService(ByVal pCLIENT_ERP_CODE As String, ByVal pSERVICE_ID As String, ByVal pLOGIN_ID As String, ByVal pQTY As Double, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetAllClientsWithServices", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetAllClientsWithServices(ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataSet
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WMS_ServicesToBillSoapChannel
        Inherits OnePlanServices_ServicesToBill.WMS_ServicesToBillSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WMS_ServicesToBillSoapClient
        Inherits System.ServiceModel.ClientBase(Of OnePlanServices_ServicesToBill.WMS_ServicesToBillSoap)
        Implements OnePlanServices_ServicesToBill.WMS_ServicesToBillSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetAllServicesNotRelated(ByVal pCLIENT_ERP_CODE As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataSet Implements OnePlanServices_ServicesToBill.WMS_ServicesToBillSoap.GetAllServicesNotRelated
            Return MyBase.Channel.GetAllServicesNotRelated(pCLIENT_ERP_CODE, pResult, pEnvironmentName)
        End Function
        
        Public Function GetAllServicesRelatedTo(ByVal pCLIENT_ERP_CODE As String, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataSet Implements OnePlanServices_ServicesToBill.WMS_ServicesToBillSoap.GetAllServicesRelatedTo
            Return MyBase.Channel.GetAllServicesRelatedTo(pCLIENT_ERP_CODE, pResult, pEnvironmentName)
        End Function
        
        Public Function RelateServiceTo(ByVal pCLIENT_ERP_CODE As String, ByVal pSERVICE_ID As String, ByVal pLOGIN_ID As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_ServicesToBill.WMS_ServicesToBillSoap.RelateServiceTo
            Return MyBase.Channel.RelateServiceTo(pCLIENT_ERP_CODE, pSERVICE_ID, pLOGIN_ID, pResult, pEnvironmentName)
        End Function
        
        Public Function UnRelateServiceTo(ByVal pCLIENT_ERP_CODE As String, ByVal pSERVICE_SEQUENCE As Integer, ByVal pLOGIN_ID As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_ServicesToBill.WMS_ServicesToBillSoap.UnRelateServiceTo
            Return MyBase.Channel.UnRelateServiceTo(pCLIENT_ERP_CODE, pSERVICE_SEQUENCE, pLOGIN_ID, pResult, pEnvironmentName)
        End Function
        
        Public Function UpdateServiceComments(ByVal pCLIENT_ERP_CODE As String, ByVal pSERVICE_ID As String, ByVal pCOMMENTS As String, ByVal pREFERENCES As String, ByVal pLOGIN_ID As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_ServicesToBill.WMS_ServicesToBillSoap.UpdateServiceComments
            Return MyBase.Channel.UpdateServiceComments(pCLIENT_ERP_CODE, pSERVICE_ID, pCOMMENTS, pREFERENCES, pLOGIN_ID, pResult, pEnvironmentName)
        End Function
        
        Public Function UpdateService(ByVal pCLIENT_ERP_CODE As String, ByVal pSERVICE_ID As String, ByVal pLOGIN_ID As String, ByVal pQTY As Double, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_ServicesToBill.WMS_ServicesToBillSoap.UpdateService
            Return MyBase.Channel.UpdateService(pCLIENT_ERP_CODE, pSERVICE_ID, pLOGIN_ID, pQTY, pResult, pEnvironmentName)
        End Function
        
        Public Function GetAllClientsWithServices(ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataSet Implements OnePlanServices_ServicesToBill.WMS_ServicesToBillSoap.GetAllClientsWithServices
            Return MyBase.Channel.GetAllClientsWithServices(pResult, pEnvironmentName)
        End Function
    End Class
End Namespace
