'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace OnePlanServices_TasksAdmin
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="OnePlanServices_TasksAdmin.WMS_TasksAdminSoap")>  _
    Public Interface WMS_TasksAdminSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateAssignedTaskUser", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UpdateAssignedTaskUser(ByVal serialNumber As Integer, ByVal wavePicking As Integer, ByVal materialId As String, ByVal pTASK_ASSIGNEDTO As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/MarkToAudit", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function MarkToAudit(ByVal pERP_DOC As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateStatusTaskUser", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UpdateStatusTaskUser(ByVal wavePicking As Integer, ByVal pNewStatus As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateTaskStatusByBin", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UpdateTaskStatusByBin(ByVal pERP_DOCUMENT As String, ByVal pNewBIN_ID As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/DeleteTask", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function DeleteTask(ByVal pTASK_SN As Long, ByRef pUserID As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/MarkAllowedToPicking", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function MarkAllowedToPicking(ByVal pWAREHOUSE_SOURCE As String, ByVal pLINE_ID As String, ByVal pERPDoc As String, ByVal pTaskOwner As String, ByVal pComments As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CreatePickingFromDemand", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CreatePickingFromDemand(ByVal pWAREHOUSE_SOURCE As String, ByVal pLINE_ID As String, ByVal pERPDoc As String, ByVal pTaskOwner As String, ByVal pComments As String, ByVal pTargetBin As Integer, ByVal pNeedsToAudit As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/TestCreatePickingFromDemand", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function TestCreatePickingFromDemand(ByVal pWAREHOUSE_SOURCE As String, ByVal pLINE_ID As String, ByVal pERPDoc As String, ByVal pTaskOwner As String, ByVal pComments As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CreatePickingManual", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CreatePickingManual(ByVal pWAREHOUSE_SOURCE As String, ByVal pLINE_ID As String, ByVal pERPDoc As String, ByVal pERPClient As String, ByVal pTaskOwner As String, ByVal pComments As String, ByVal pQty As Double, ByVal pMaterialID As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CreateReplenishment", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CreateReplenishment(ByVal pWAREHOUSE_SOURCE As String, ByVal pWAREHOUSE_TARGET As String, ByVal pTaskOwner As String, ByVal pTASK_ASSIGNEDTO As String, ByVal pMATERIAL_CODE As String, ByVal pMATERIAL_BARCODE As String, ByVal pLOCATION_SPOT_SOURCE As String, ByVal pLOCATION_SPOT_TARGET As String, ByVal p_QTY As Double, ByVal pQUANTITY_ASSIGNED As Double, ByVal pBIN_SOURCE As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetMyPickingTasks", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetMyPickingTasks(ByVal pLOGIN_ID As String, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetBestLocationToRelocFromStandBy", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetBestLocationToRelocFromStandBy(ByVal pWAREHOUSE As String, ByVal pBIN As String, ByVal pMATERIAL As String, ByVal pQTY As Double, ByVal pSTANDBY_LOCATION As String, ByVal pEnvironmentName As String, ByRef pResult As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateTaskStartDate", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UpdateTaskStartDate(ByVal pTASK_SN As Long, ByRef pUserID As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AddLog", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function AddLog(ByVal pLOGIN_ID As String, ByVal pTRANS_TYPE As String, ByVal pBIN_ID As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CleanUpDataForNewCampaign", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CleanUpDataForNewCampaign(ByVal pLogin As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/MarkDocumentAsVoid", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function MarkDocumentAsVoid(ByVal pERP_DOCUMENT As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RestoreDocumentFromVoid", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RestoreDocumentFromVoid(ByVal pERP_DOCUMENT As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AssignLineToDemmand", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function AssignLineToDemmand(ByVal pSector As String, ByVal pRuta As String, ByVal pIncluyeAsignados As Boolean, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RemovePedidoFromCtrlBin", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RemovePedidoFromCtrlBin(ByVal pTargetBin As Integer, ByVal pAssignedUser As String, ByVal pLinea As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AddNewBINClosedToCtrlBin", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function AddNewBINClosedToCtrlBin(ByVal pERPDoc As String, ByVal pClosedBin As Integer, ByVal pTargetBin As Integer, ByVal pAssignedUser As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AddReassignedBINtoControlTableCall", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function AddReassignedBINtoControlTableCall(ByVal pERPDoc As String, ByVal pTargetBin As Integer, ByVal pColumna As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CreatePackagesCountTask", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CreatePackagesCountTask(ByVal pWAREHOUSE_SOURCE As String, ByVal pLINE_ID As String, ByVal pERPDoc As String, ByVal pERPClient As String, ByVal pTaskOwner As String, ByVal pComments As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_all_counts", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_all_counts(ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/set_counting", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function set_counting(ByRef pCOUNT_ID As Integer, ByVal pCREATED_BY As String, ByVal pCOUNT_TYPE As String, ByVal pACCURACY As Decimal, ByVal pFiltro As System.Data.DataSet, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_locations_count", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_locations_count(ByVal pFiltro As System.Data.DataSet, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_all_count_tasks", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_all_count_tasks(ByVal pCOUNT_ID As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/assing_counting_task", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function assing_counting_task(ByVal pTasks As System.Data.DataSet, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_count_dif", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_count_dif(ByVal pCOUNT_ID As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/cancel_counting_task", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function cancel_counting_task(ByVal pTasks As System.Data.DataSet, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateStatusTaskUserBySerialNumber", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UpdateStatusTaskUserBySerialNumber(ByVal pTASK_SN As Long, ByVal pNewStatus As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/DeleteTaskBySerialNumber", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function DeleteTaskBySerialNumber(ByVal serialNumber As Integer, ByRef pUserID As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateTaskByTaskId", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UpdateTaskByTaskId(ByVal taskId As Integer, ByRef newStatus As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/DeleteCountingTask", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function DeleteCountingTask(ByVal taskId As Integer, ByRef user As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WMS_TasksAdminSoapChannel
        Inherits OnePlanServices_TasksAdmin.WMS_TasksAdminSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WMS_TasksAdminSoapClient
        Inherits System.ServiceModel.ClientBase(Of OnePlanServices_TasksAdmin.WMS_TasksAdminSoap)
        Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function UpdateAssignedTaskUser(ByVal serialNumber As Integer, ByVal wavePicking As Integer, ByVal materialId As String, ByVal pTASK_ASSIGNEDTO As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.UpdateAssignedTaskUser
            Return MyBase.Channel.UpdateAssignedTaskUser(serialNumber, wavePicking, materialId, pTASK_ASSIGNEDTO, pResult, pEnvironmentName)
        End Function
        
        Public Function MarkToAudit(ByVal pERP_DOC As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.MarkToAudit
            Return MyBase.Channel.MarkToAudit(pERP_DOC, pResult, pEnvironmentName)
        End Function
        
        Public Function UpdateStatusTaskUser(ByVal wavePicking As Integer, ByVal pNewStatus As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.UpdateStatusTaskUser
            Return MyBase.Channel.UpdateStatusTaskUser(wavePicking, pNewStatus, pResult, pEnvironmentName)
        End Function
        
        Public Function UpdateTaskStatusByBin(ByVal pERP_DOCUMENT As String, ByVal pNewBIN_ID As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.UpdateTaskStatusByBin
            Return MyBase.Channel.UpdateTaskStatusByBin(pERP_DOCUMENT, pNewBIN_ID, pResult, pEnvironmentName)
        End Function
        
        Public Function DeleteTask(ByVal pTASK_SN As Long, ByRef pUserID As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.DeleteTask
            Return MyBase.Channel.DeleteTask(pTASK_SN, pUserID, pResult, pEnvironmentName)
        End Function
        
        Public Function MarkAllowedToPicking(ByVal pWAREHOUSE_SOURCE As String, ByVal pLINE_ID As String, ByVal pERPDoc As String, ByVal pTaskOwner As String, ByVal pComments As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.MarkAllowedToPicking
            Return MyBase.Channel.MarkAllowedToPicking(pWAREHOUSE_SOURCE, pLINE_ID, pERPDoc, pTaskOwner, pComments, pResult, pEnvironmentName)
        End Function
        
        Public Function CreatePickingFromDemand(ByVal pWAREHOUSE_SOURCE As String, ByVal pLINE_ID As String, ByVal pERPDoc As String, ByVal pTaskOwner As String, ByVal pComments As String, ByVal pTargetBin As Integer, ByVal pNeedsToAudit As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.CreatePickingFromDemand
            Return MyBase.Channel.CreatePickingFromDemand(pWAREHOUSE_SOURCE, pLINE_ID, pERPDoc, pTaskOwner, pComments, pTargetBin, pNeedsToAudit, pResult, pEnvironmentName)
        End Function
        
        Public Function TestCreatePickingFromDemand(ByVal pWAREHOUSE_SOURCE As String, ByVal pLINE_ID As String, ByVal pERPDoc As String, ByVal pTaskOwner As String, ByVal pComments As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.TestCreatePickingFromDemand
            Return MyBase.Channel.TestCreatePickingFromDemand(pWAREHOUSE_SOURCE, pLINE_ID, pERPDoc, pTaskOwner, pComments, pResult, pEnvironmentName)
        End Function
        
        Public Function CreatePickingManual(ByVal pWAREHOUSE_SOURCE As String, ByVal pLINE_ID As String, ByVal pERPDoc As String, ByVal pERPClient As String, ByVal pTaskOwner As String, ByVal pComments As String, ByVal pQty As Double, ByVal pMaterialID As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.CreatePickingManual
            Return MyBase.Channel.CreatePickingManual(pWAREHOUSE_SOURCE, pLINE_ID, pERPDoc, pERPClient, pTaskOwner, pComments, pQty, pMaterialID, pResult, pEnvironmentName)
        End Function
        
        Public Function CreateReplenishment(ByVal pWAREHOUSE_SOURCE As String, ByVal pWAREHOUSE_TARGET As String, ByVal pTaskOwner As String, ByVal pTASK_ASSIGNEDTO As String, ByVal pMATERIAL_CODE As String, ByVal pMATERIAL_BARCODE As String, ByVal pLOCATION_SPOT_SOURCE As String, ByVal pLOCATION_SPOT_TARGET As String, ByVal p_QTY As Double, ByVal pQUANTITY_ASSIGNED As Double, ByVal pBIN_SOURCE As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.CreateReplenishment
            Return MyBase.Channel.CreateReplenishment(pWAREHOUSE_SOURCE, pWAREHOUSE_TARGET, pTaskOwner, pTASK_ASSIGNEDTO, pMATERIAL_CODE, pMATERIAL_BARCODE, pLOCATION_SPOT_SOURCE, pLOCATION_SPOT_TARGET, p_QTY, pQUANTITY_ASSIGNED, pBIN_SOURCE, pResult, pEnvironmentName)
        End Function
        
        Public Function GetMyPickingTasks(ByVal pLOGIN_ID As String, ByRef pResult As String, ByVal pEnvironmentName As String) As System.Data.DataSet Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.GetMyPickingTasks
            Return MyBase.Channel.GetMyPickingTasks(pLOGIN_ID, pResult, pEnvironmentName)
        End Function
        
        Public Function GetBestLocationToRelocFromStandBy(ByVal pWAREHOUSE As String, ByVal pBIN As String, ByVal pMATERIAL As String, ByVal pQTY As Double, ByVal pSTANDBY_LOCATION As String, ByVal pEnvironmentName As String, ByRef pResult As String) As String Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.GetBestLocationToRelocFromStandBy
            Return MyBase.Channel.GetBestLocationToRelocFromStandBy(pWAREHOUSE, pBIN, pMATERIAL, pQTY, pSTANDBY_LOCATION, pEnvironmentName, pResult)
        End Function
        
        Public Function UpdateTaskStartDate(ByVal pTASK_SN As Long, ByRef pUserID As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.UpdateTaskStartDate
            Return MyBase.Channel.UpdateTaskStartDate(pTASK_SN, pUserID, pResult, pEnvironmentName)
        End Function
        
        Public Function AddLog(ByVal pLOGIN_ID As String, ByVal pTRANS_TYPE As String, ByVal pBIN_ID As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.AddLog
            Return MyBase.Channel.AddLog(pLOGIN_ID, pTRANS_TYPE, pBIN_ID, pResult, pEnvironmentName)
        End Function
        
        Public Function CleanUpDataForNewCampaign(ByVal pLogin As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.CleanUpDataForNewCampaign
            Return MyBase.Channel.CleanUpDataForNewCampaign(pLogin, pResult, pEnvironmentName)
        End Function
        
        Public Function MarkDocumentAsVoid(ByVal pERP_DOCUMENT As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.MarkDocumentAsVoid
            Return MyBase.Channel.MarkDocumentAsVoid(pERP_DOCUMENT, pResult, pEnvironmentName)
        End Function
        
        Public Function RestoreDocumentFromVoid(ByVal pERP_DOCUMENT As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.RestoreDocumentFromVoid
            Return MyBase.Channel.RestoreDocumentFromVoid(pERP_DOCUMENT, pResult, pEnvironmentName)
        End Function
        
        Public Function AssignLineToDemmand(ByVal pSector As String, ByVal pRuta As String, ByVal pIncluyeAsignados As Boolean, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.AssignLineToDemmand
            Return MyBase.Channel.AssignLineToDemmand(pSector, pRuta, pIncluyeAsignados, pResult, pEnvironmentName)
        End Function
        
        Public Function RemovePedidoFromCtrlBin(ByVal pTargetBin As Integer, ByVal pAssignedUser As String, ByVal pLinea As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.RemovePedidoFromCtrlBin
            Return MyBase.Channel.RemovePedidoFromCtrlBin(pTargetBin, pAssignedUser, pLinea, pResult, pEnvironmentName)
        End Function
        
        Public Function AddNewBINClosedToCtrlBin(ByVal pERPDoc As String, ByVal pClosedBin As Integer, ByVal pTargetBin As Integer, ByVal pAssignedUser As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.AddNewBINClosedToCtrlBin
            Return MyBase.Channel.AddNewBINClosedToCtrlBin(pERPDoc, pClosedBin, pTargetBin, pAssignedUser, pResult, pEnvironmentName)
        End Function
        
        Public Function AddReassignedBINtoControlTableCall(ByVal pERPDoc As String, ByVal pTargetBin As Integer, ByVal pColumna As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.AddReassignedBINtoControlTableCall
            Return MyBase.Channel.AddReassignedBINtoControlTableCall(pERPDoc, pTargetBin, pColumna, pResult, pEnvironmentName)
        End Function
        
        Public Function CreatePackagesCountTask(ByVal pWAREHOUSE_SOURCE As String, ByVal pLINE_ID As String, ByVal pERPDoc As String, ByVal pERPClient As String, ByVal pTaskOwner As String, ByVal pComments As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.CreatePackagesCountTask
            Return MyBase.Channel.CreatePackagesCountTask(pWAREHOUSE_SOURCE, pLINE_ID, pERPDoc, pERPClient, pTaskOwner, pComments, pResult, pEnvironmentName)
        End Function
        
        Public Function get_all_counts(ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.get_all_counts
            Return MyBase.Channel.get_all_counts(pEnvironmentName, pResult)
        End Function
        
        Public Function set_counting(ByRef pCOUNT_ID As Integer, ByVal pCREATED_BY As String, ByVal pCOUNT_TYPE As String, ByVal pACCURACY As Decimal, ByVal pFiltro As System.Data.DataSet, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.set_counting
            Return MyBase.Channel.set_counting(pCOUNT_ID, pCREATED_BY, pCOUNT_TYPE, pACCURACY, pFiltro, pEnvironmentName, pResult)
        End Function
        
        Public Function get_locations_count(ByVal pFiltro As System.Data.DataSet, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.get_locations_count
            Return MyBase.Channel.get_locations_count(pFiltro, pEnvironmentName, pResult)
        End Function
        
        Public Function get_all_count_tasks(ByVal pCOUNT_ID As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.get_all_count_tasks
            Return MyBase.Channel.get_all_count_tasks(pCOUNT_ID, pEnvironmentName, pResult)
        End Function
        
        Public Function assing_counting_task(ByVal pTasks As System.Data.DataSet, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.assing_counting_task
            Return MyBase.Channel.assing_counting_task(pTasks, pEnvironmentName, pResult)
        End Function
        
        Public Function get_count_dif(ByVal pCOUNT_ID As Integer, ByVal pEnvironmentName As String, ByRef pResult As String) As System.Data.DataSet Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.get_count_dif
            Return MyBase.Channel.get_count_dif(pCOUNT_ID, pEnvironmentName, pResult)
        End Function
        
        Public Function cancel_counting_task(ByVal pTasks As System.Data.DataSet, ByVal pEnvironmentName As String, ByRef pResult As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.cancel_counting_task
            Return MyBase.Channel.cancel_counting_task(pTasks, pEnvironmentName, pResult)
        End Function
        
        Public Function UpdateStatusTaskUserBySerialNumber(ByVal pTASK_SN As Long, ByVal pNewStatus As Integer, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.UpdateStatusTaskUserBySerialNumber
            Return MyBase.Channel.UpdateStatusTaskUserBySerialNumber(pTASK_SN, pNewStatus, pResult, pEnvironmentName)
        End Function
        
        Public Function DeleteTaskBySerialNumber(ByVal serialNumber As Integer, ByRef pUserID As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.DeleteTaskBySerialNumber
            Return MyBase.Channel.DeleteTaskBySerialNumber(serialNumber, pUserID, pResult, pEnvironmentName)
        End Function
        
        Public Function UpdateTaskByTaskId(ByVal taskId As Integer, ByRef newStatus As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.UpdateTaskByTaskId
            Return MyBase.Channel.UpdateTaskByTaskId(taskId, newStatus, pResult, pEnvironmentName)
        End Function
        
        Public Function DeleteCountingTask(ByVal taskId As Integer, ByRef user As String, ByRef pResult As String, ByVal pEnvironmentName As String) As Boolean Implements OnePlanServices_TasksAdmin.WMS_TasksAdminSoap.DeleteCountingTask
            Return MyBase.Channel.DeleteCountingTask(taskId, user, pResult, pEnvironmentName)
        End Function
    End Class
End Namespace
